name: Deploy to EC2 on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ 13.232.221.11 }}
        username: ${{ ubuntu }}
        key: ${{ MIIEpQIBAAKCAQEAxW/pCklPcjHZaAABbsrTpFQYgoz1s7I9nTghlahYT6KWBAYNKbp1UaICtHBSe7LCFBxUiEgpawM+hMD4YsuLjE0xtZ0t8jIW/IXv3ON9vMg7OUsXDqNjUOvnt5dx7Kbx43iBmPa2v/gQlXryCLx+I4QM7GZva/N0pAQLVKy9wspMFYnVKQ9BMkXYyCYmdcA4Cvgz0nbaAwxEoLubkZw45kbHRgtu1uiKCgWs5cCt1OexxWC1REDJV6r84l5h8Cr/WEVjMOnlGcefdnUoNG4EBUmaCr/5LdCk/zOmrkTZjBNLFWFw8tHo3O85ifl4C9iS/rZAMYaQzzEhJgw5yA3f9wIDAQABAoIBAQC9TNNvnWKi5tDAOmElTSsm/8qQQX7C0D7rIwpwZ3xkvkp/iR3NyIz7vA5D2v36xCX5CkCyeh3cELw8pJiCgQ5HcywaKZ4H/aa0b+bPLv87pe/CuxBcZKOwzr7Y9Eey005Q/xWjB8movbuI1tyBK9j1TILnlj92jXJkX8xNX2KCA6oNkWPpyR6aniLLDlGeu1XjYZ89L7RESnBfUzCGa9NENnikjiKn/OXUSYbW7fQ8o2Zfbr72n97XpYAaj6oJPrc2nKJgso95K/YVjW7dMtRpNo7TSQxHIdbRKF25lpM6mNrGgllq2MxSmomqoCAqll0Ss7v+wqIQ6FTLzdFFw/ohAoGBAP5nejI8yRHgdPqL4ZHkJOt5Z9KDH5+B8q+uuNOg+iUQtFFNZn9bGJdtBLEtFJrfgMH/bAhMkrc8t6sgqo+8m0VMQ2M8tRUgXfSJ9y2Xo8+6WSk9s+uU4woVgnW40ofZH2dywsEJlBFbwjNHJHk7A7AuNQkPIMoVyrTBEJ9JZxZLAoGBAMas9IeMYcoSOW+xMKF8zv0c1b5Aythy7WZMQxZRrTvPJO3mfr1txEF7pdMoZaDO4QAn6KfLxBTHpFTvJ2zd42P68jRfvgsp8hqlS45kyd8tL6ujxNLIcJZrTPkWN6YX4Drr2ezBx2tZDw3mOobc/qOD07JbhaHhRIDxk9LdmwGFAoGANuyWOCRhcKeZ+cGbaIjt45ypaox+lkxS3dUF+EKn3rq1g1wHhfVf4MlbmvjVmv4n6TpA06XcgwzrxlleGXwptZNadSFVIwOC5Vmn8MLtTdq4hyvYHUNepP2x1cKaSVP58LaZD14HBpxd1/5DBJ1WFYJUVulaNebwhYetFAaf5/MCgYEAg89LjIJ+fmoI4SlVck4zpYnz5P1nlqLpDe2atLwLipqrjYpWm6avhiJaqfUrN70JWekgWfK+bGrng9IG/htYOYTMHCNJGm8ByNvRfO8xX3fDIMTOWGnTCHi34Kn00aUVhwHi20jU3UuAyV/thHwqFKHpWXOO/Q9PO50KzeNoa2ECgYEAzoGrnz8FrP173u3grtBQrl8j0ZZ/3e4Dmi4FL0eU4Efx76sr2ktKn0hQPW7VtMS1NRATC3e7K7ZEwN404kzA/X631dm8jK+qDeeAJSu+eEI8wdQ8CVZkA0pWpDUXN+UEIR2A6300oJa4M8hFzNPxilvA4+YrP/rPv4MLWfHTFgo= }}
        script: |
          cd prasan_ban_backend
          git pull origin main
          npm install
          npm run build  # only if React
          pm2 restart all
